
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [4]:
import numpy as np
import matplotlib as plt

In [5]:
List_arr = ([1,2,3,4,5,6,7,8,9,])

In [6]:
List_arr = np.array(List_arr)

In [7]:
List_arr.ndim

1

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [8]:
newarr = np.array(List_arr).reshape(3, 3)
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Access the element at the second row, second column.


In [9]:
print(newarr[1,1])

5


###                                                               OR

In [10]:
print(newarr[1 , 1:2])

[5]


Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [11]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

Sum = array1 + array2
print(Sum)  


[5 7 9]


In [12]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

Subtract = -array1 + array2
print(Subtract)  


[3 3 3]


In [13]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

Multiplication = array1 * array2
print(Multiplication)  


[ 4 10 18]


In [14]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

Division = array1 / array2
print(Division)  


[0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [15]:
array = np.array([1, 2, 3, 4, 5])

sum = np.sum(array)
print(sum)

15


In [16]:
array = np.array([1, 2, 3, 4, 5])

mean = np.mean(array)
print(mean)

3.0


In [17]:
array = np.array([1, 2, 3, 4, 5])

standard_deviation = np.std(array)
print(standard_deviation)

1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [18]:
array = np.array([1, 2, 3, 4, 5,6])
new = np.array(array).reshape(2, 3)
print(new)

[[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [19]:
array5x5 = np.random.randint(0, 100,(5,5))
print (array5x5)

[[68 72 80 31 58]
 [30 43 90 73 81]
 [79  3 12 76 78]
 [30  1 68 51 11]
 [ 3 53 61 37 28]]


Replace all values in the sub-array with a specific value.


In [20]:
array5x5[1:3, 1:3] = 22 #=Bday
print(array5x5)

[[68 72 80 31 58]
 [30 22 22 73 81]
 [79 22 22 76 78]
 [30  1 68 51 11]
 [ 3 53 61 37 28]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [21]:
array2 = np.array([[1,2],[3,4],[5,6],[7,8]])
subarray = array2[1:3]
print(subarray)

[[3 4]
 [5 6]]



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [22]:
array2d =[[0, 1, 2],
          [0, 1, 2],         
          [0, 1, 2]]
array2d = np.array([[0, 1, 2],
          [0, 1, 2],         
          [0, 1, 2]])
print(array2d)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [23]:
array1d = np.array([10, 19, 28])
output= array2d + array1d
print(output)

[[10 20 30]
 [10 20 30]
 [10 20 30]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [27]:
array1 = np.random.randint(0, 10, (3, 3))
array2 = np.random.randint(0, 10, (3, 3))

print("Array Number 1:")
print(array1)
print("Array Number 2:")
print(array2)


Array Number 1:
[[2 9 0]
 [8 4 9]
 [6 3 8]]
Array Number 2:
[[2 0 5]
 [4 8 9]
 [1 9 8]]


In [28]:
horizontal_concat = np.concatenate((array1, array2), axis=1)
print("Horizontal concatenation:")
print(horizontal_concat)

Horizontal concatenation:
[[2 9 0 2 0 5]
 [8 4 9 4 8 9]
 [6 3 8 1 9 8]]


In [29]:
vertical_concat = np.concatenate((array1, array2), axis=0)
print("ceryical concatenation:")
print(vertical_concat)

ceryical concatenation:
[[2 9 0]
 [8 4 9]
 [6 3 8]
 [2 0 5]
 [4 8 9]
 [1 9 8]]


In [33]:
horizontal_concat = ((array1, array2),)#I juts removed the concatenotion fucntion
print("Horizontal concatenation:")
print(horizontal_concat)

Horizontal concatenation:
((array([[2, 9, 0],
       [8, 4, 9],
       [6, 3, 8]]), array([[2, 0, 5],
       [4, 8, 9],
       [1, 9, 8]])),)


In [36]:
vertical_concat = ((array1, array2))# Same here, just removed the concatenation function to change it back to the way it was
print("ceryical concatenation:")
print(vertical_concat)

ceryical concatenation:
(array([[2, 9, 0],
       [8, 4, 9],
       [6, 3, 8]]), array([[2, 0, 5],
       [4, 8, 9],
       [1, 9, 8]]))


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [38]:
arrayb = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]
frequency = {}#to store the frequency of each number
for num in array:
    if num in frequency:
        frequency[num] += 1
    else:
        frequency[num] = 1

mode = max(frequency, key=frequency.get)
print("Mode of the array is =", mode)



Mode of the array is = 1


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

